import Head from 'next/head'
import { Container, Grid, Card, CardMedia, Typography } from '@mui/material'
import Layout from '../app/components/TopBarComponents/Layout'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        <Layout>
          <Container>
            <Grid container spacing={12} style={{marginTop: "15%"}}>
            <Grid item xs={12} sm={6} md={3}>
                <Link href="/Registration"> {/* Adiciona o link para o Card */}
                 
                    <Card style={{textAlign: 'center',background:'transparent',border:'none',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center'}}>
                      <CardMedia 
                        component="img"
                        height="fit-content"
                        width='fit-content'
                        image='https://firebasestorage.googleapis.com/v0/b/chat-dos-otarios.appspot.com/o/ceab%2Fresume.png?alt=media&token=6edbaf5e-7e2b-40a0-a3e2-9811e3631a75'
                        alt=""
                      />
                      <Typography color='#FFFF' mt={3}  variant="h5">Cadastro</Typography>
                      <Typography color='#FFFF' mt={27}  variant="h5"></Typography>
                    </Card>
                 
                </Link>
              </Grid>
              <Grid item xs={12} sm={6} md={3}>
                <Link href="/UpdateData"> {/* Adiciona o link para o Card */}
                 
                    <Card style={{textAlign: 'center',background:'transparent',border:'none',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center'}}>
                      <CardMedia 
                        component="img"
                        height="fit-content"
                        width='fit-content'
                        image='https://firebasestorage.googleapis.com/v0/b/chat-dos-otarios.appspot.com/o/ceab%2Fupdate.png?alt=media&token=bc1e2318-041e-4154-8f27-8d0a9faa80ae'
                        alt=""
                      />
                      <Typography color='#FFFF' mt={3}  variant="h5">Atualização</Typography>
                      <Typography color='#FFFF' mt={27}  variant="h5"></Typography>
                    </Card>
                 
                </Link>
              </Grid>
              <Grid item xs={12} sm={6} md={3}>
                <Link href="/TabelaDados"> {/* Adiciona o link para o Card */}
                 
                    <Card style={{textAlign: 'center',background:'transparent',border:'none',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center'}}>
                      <CardMedia 
                        component="img"
                        height="fit-content"
                        width='fit-content'
                        image='https://firebasestorage.googleapis.com/v0/b/chat-dos-otarios.appspot.com/o/ceab%2Fchecklist.png?alt=media&token=95d85403-ac4e-49a2-a546-cd7615c6ff50'
                        alt=""
                      />
                      <Typography color='#FFFF' mt={3}  variant="h5">Lista</Typography>
                      <Typography color='#FFFF' mt={27}  variant="h5"></Typography>
                    </Card>
                
                </Link>
              </Grid>
              <Grid item xs={12} sm={6} md={3}>
                <Link href="https://script.google.com/macros/s/AKfycbxHQHqhYDae5zRtmHcIoHLlIlBkJKIdxBy__-lm4O_nMIHJ0T3tt6r28rwHBhvykGsKKA/exec">
                  
                    <Card style={{textAlign: 'center',background:'transparent',border:'none',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center'}}>
                      <CardMedia 
                        component="img"
                        height="fit-content"
                        width='fit-content'
                        image='https://firebasestorage.googleapis.com/v0/b/chat-dos-otarios.appspot.com/o/ceab%2Fclock.png?alt=media&token=061a08d4-b13c-41bb-952b-a1a53b0f9ca3'
                        alt=""
                      />
                      <Typography color='#FFFF' mt={3}  variant="h5">Frequência</Typography>
                      <Typography color='#FFFF' mt={27}  variant="h5"></Typography>
                    </Card>
                  
                </Link>
              </Grid>

               <Grid item xs={12} sm={6} md={3}>
                <Link href="https://docs.google.com/spreadsheets/d/1TjtX-JT-c3f8Mb_ujSx61IQ2i6Zha4ZPn8by_HyYXjw/edit?gid=1340376132#gid=1340376132">
                  
                    <Card style={{textAlign: 'center',background:'transparent',border:'none',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center'}}>
                      <CardMedia 
                        component="img"
                        height="fit-content"
                        width='fit-content'
                        image='https://firebasestorage.googleapis.com/v0/b/chat-dos-otarios.appspot.com/o/ceab%2Fclock.png?alt=media&token=061a08d4-b13c-41bb-952b-a1a53b0f9ca3'
                        alt=""
                      />
                      <Typography color='#FFFF' mt={3}  variant="h5">Lista de Desligados/cadastro de temporários e lista de necessidades</Typography>
                      <Typography color='#FFFF' mt={27}  variant="h5"></Typography>
                    </Card>
                  
                </Link>
              </Grid>

             
            </Grid>
          </Container>
       </Layout>
      </main>
    </>
  )
}
